package rbac

import "std"

// initial addresses
const (
	ADMIN   std.Address = "g17290cwvmrapvp869xfnhhawa8sm9edpufzat7d"
	DEV_OPS std.Address = "g1mjvd83nnjee3z2g7683er55me9f09688pd4mj9"

	COMMUNITY_POOL_ADDR std.Address = "g100fnnlz5eh87p5hvwt8pf279lxaelm8k8md049"
	GOV_GOVERNANCE_ADDR std.Address = "g17s8w2ve7k85fwfnrk59lmlhthkjdted8whvqxd"
	GOV_STAKER_ADDR     std.Address = "g17e3ykyqk9jmqe2y9wxe9zhep3p7cw56davjqwa"
	GOV_XGNS_ADDR       std.Address = "g1wwh55uwzlz2zzr2qcvvxf83qhcvmx2t8779l9r"

	POOL_ADDR     std.Address = "g148tjamj80yyrm309z7rk690an22thd2l3z8ank"
	POSITION_ADDR std.Address = "g1q646ctzhvn60v492x8ucvyqnrj2w30cwh6efk5"
	ROUTER_ADDR   std.Address = "g1lm2l7tf49h3mykesct7rhfml30yx8dw5xrval7"
	STAKER_ADDR   std.Address = "g1cceshmzzlmrh7rr3z30j2t5mrvsq9yccysw9nu"

	EMISSION_ADDR     std.Address = "g10xg6559w9e93zfttlhvdmaaa0er3zewcr7nh20"
	LAUNCHPAD_ADDR    std.Address = "g122mau2lp2rc0scs8d27pkkuys4w54mdy2tuer3"
	PROTOCOL_FEE_ADDR std.Address = "g1f7wpek7q67tkns27sw495u5yuu3a5wwjxw5l6l"
)
