#!/usr/bin/env bash
set -euo pipefail

PERF_DIR=$(cd "$(dirname "$0")" && pwd)
PROJECT_ROOT=$(cd "$PERF_DIR/../.." && pwd)
GNO_REPO=${GNO_REPO:-"$HOME/gno-core"}
MAX_GAS=${MAX_GAS:-10000000000}
WORKLOAD=gnoswap-transactions
RUN_ID=$(date -u +%Y%m%d_%H%M%S)
RUN_DIR=${RUN_DIR:-"$PERF_DIR/results/$RUN_ID"}
GNODEV="$GNO_REPO/contribs/gnodev/build/gnodev"
NODE_PID=
SAMPLER_PID=
STARTED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
FINISHED_AT=null

case "$PROJECT_ROOT" in
  /tmp/* | /private/tmp/*) ;;
  *)
    printf 'run this benchmark from a fresh /tmp copy; deployment deletes Gno test files\n' >&2
    exit 1
    ;;
esac

ADMIN_ADDRESS=$(gnokey list | awk '$2 == "gnoswap_admin" { print $6 }')

if [[ -z "$ADMIN_ADDRESS" ]]; then
  printf 'gnokey account gnoswap_admin was not found\n' >&2
  exit 1
fi

write_metadata() {
  printf '{\n  "gnoswap_commit": "%s",\n  "gno_commit": "%s",\n  "gnodev_sha256": "%s",\n  "go_version": "%s",\n  "max_gas": %s,\n  "genesis": "generated by gnodev",\n  "workload": "%s",\n  "started_at": "%s",\n  "finished_at": %s\n}\n' \
    "$(git -C "$PROJECT_ROOT" rev-parse HEAD)" \
    "$(git -C "$GNO_REPO" rev-parse HEAD)" \
    "$(shasum -a 256 "$GNODEV" | awk '{print $1}')" \
    "$(go version)" "$MAX_GAS" "$WORKLOAD" "$STARTED_AT" "$FINISHED_AT" \
    > "$RUN_DIR/metadata.json"
}

cleanup() {
  status=$?
  trap - EXIT
  if [[ -n "$SAMPLER_PID" ]]; then
    kill "$SAMPLER_PID" 2>/dev/null || true
    wait "$SAMPLER_PID" 2>/dev/null || true
  fi
  if [[ -n "$NODE_PID" ]]; then
    kill "$NODE_PID" 2>/dev/null || true
    wait "$NODE_PID" 2>/dev/null || true
  fi
  FINISHED_AT="\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
  write_metadata
  python3 "$PERF_DIR/collect_blocks.py" "$RUN_DIR/node.jsonl" "$RUN_DIR/blocks.jsonl" || status=$?
  printf 'Results: %s\n' "$RUN_DIR"
  exit "$status"
}
trap cleanup EXIT
trap 'exit 130' INT TERM

mkdir -p "$RUN_DIR"
make -C "$GNO_REPO/contribs/gnodev" build
write_metadata
printf 'timestamp,cpu_percent,rss_kb\n' > "$RUN_DIR/resources.csv"

cd "$PROJECT_ROOT"
"$GNODEV" local -chain-id dev -log-format json -max-gas "$MAX_GAS" \
  -add-account test1=1000000000000000ugnot \
  -add-account gnoswap_admin=1000000000000000ugnot \
  -paths gno.land/p/nt/bptree/v0,gno.land/p/nt/ufmt/v0,gno.land/p/onbloc/json,gno.land/p/nt/ownable/v0,gno.land/p/demo/tokens/grc20,gno.land/p/demo/tokens/grc721,gno.land/r/demo/defi/foo20,gno.land/r/sys/users,gno.land/r/gnoland/wugnot,gno.land/r/demo/defi/grc20reg \
  > "$RUN_DIR/node.jsonl" 2>&1 &
NODE_PID=$!

(
  while kill -0 "$NODE_PID" 2>/dev/null; do
    read -r cpu rss < <(ps -p "$NODE_PID" -o %cpu=,rss=)
    printf '%s,%s,%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$cpu" "$rss"
    sleep 1
  done
) >> "$RUN_DIR/resources.csv" &
SAMPLER_PID=$!

for _ in {1..60}; do
  if curl -fsS http://127.0.0.1:26657/status >/dev/null; then
    break
  fi
  if ! kill -0 "$NODE_PID" 2>/dev/null; then
    printf 'gnodev exited before RPC became ready\n' >&2
    exit 1
  fi
  sleep 1
done
curl -fsS http://127.0.0.1:26657/status >/dev/null

make -C "$PROJECT_ROOT/tests" patch-admin-address ENV=default "ADDR_ADMIN=$ADMIN_ADDRESS"
make -C "$PROJECT_ROOT/tests" deploy ENV=default "ADDR_ADMIN=$ADMIN_ADDRESS"
gnokey query vm/qfile -remote 127.0.0.1:26657 \
  -data gno.land/r/gnoswap/test_token/test_usdc > "$RUN_DIR/qfile.txt"
gnokey query vm/qeval -remote 127.0.0.1:26657 \
  -data "gno.land/r/gnoswap/test_token/test_usdc.BalanceOf(\"$ADMIN_ADDRESS\")" > "$RUN_DIR/qeval.txt"
ADDR_ADMIN="$ADMIN_ADDRESS" RESULTS_DIR="$RUN_DIR" RESULT_FILE="$RUN_DIR/transactions.json" \
  "$PERF_DIR/run_benchmark.sh"
