package staker

// import (
// 	"encoding/base64"
// 	"std"
// 	"strings"
// 	"testing"

// 	"gno.land/p/demo/avl"
// )

// func TestApiGetIncentivesInfo(t *testing.T) {
// 	tagii := ApiGetIncentivesInfo()
// 	// println(tagii)
// }

// func TestApiGetStakesInfo(t *testing.T) {
// 	tagsi := ApiGetStakesInfo()
// 	// println(tagsi)
// }

// func TestApiGetRewardInfo(t *testing.T) {
// 	tagri := ApiGetRewardInfo()
// 	// println(tagri)
// }
