name: Release Management

on:
  push:
    branches:
      - main
    paths:
      - 'CHANGELOG.md'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get version from CHANGELOG
        id: changelog
        run: |
          VERSION=$(grep -m 1 "## \[.*\]" CHANGELOG.md | grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Create Release
        if: steps.changelog.outputs.version != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.changelog.outputs.version }}
        run: |
          if ! git tag | grep -q "^v$VERSION$"; then
            # Extract changelog content for this version
            CHANGELOG_CONTENTS=$(awk "/## \[$VERSION\]/,/## \[/{ if (!/## \[$VERSION\]/ && !/## \[/) print }" CHANGELOG.md)
            
            # Create and push tag
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git tag -a "v$VERSION" -m "Release version $VERSION"
            git push origin "v$VERSION"
            
            # Create GitHub release
            gh release create "v$VERSION" \
              --title "Release v$VERSION" \
              --notes "$CHANGELOG_CONTENTS" \
              --draft=false \
              --prerelease=false
          fi
