name: txtar-test
'on':
  pull_request:
    branches:
      - main
jobs:
  txtar-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run txtar tests
        run: |
          cd tests/integration
          export INMEMORY_TS=true
          export NO_SEQ_TS=true
          go test -v . -run Testdata 
